let mode='image', fileName='', imageUrl=null, imageSize={width:1000,height:700}, pages=[], pageIndex=0, selectedId=null, busy=false;
const $=id=>document.getElementById(id); const uid=()=>Math.random().toString(36).slice(2,10);
const state={get items(){return mode==='image'?(pages[0]?.items||[]):(pages[pageIndex]?.items||[])}}; const emptyTemplate=document.getElementById('emptyState').cloneNode(true);
function setStatus(s,b=false){$('status').textContent=s;$('dot').className=b?'dot busy':'dot'}
function openFile(){$('fileInput').click()}
$('uploadBtn').onclick=openFile;$('chooseBtn').onclick=openFile;
$('fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;fileName=f.name;busy=true;setStatus('Loading document…',true);try{if(f.type.startsWith('image/'))await loadImage(f);else if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'))await loadPdf(f);else throw Error('Choose PNG, JPG, WEBP, or PDF.')}catch(err){setStatus(err.message||'Could not open file.')}finally{busy=false}};
async function loadImage(file){const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{imageUrl=url;imageSize={width:img.naturalWidth,height:img.naturalHeight};pages=[{dataUrl:url,width:img.naturalWidth,height:img.naturalHeight,items:[]}];pageIndex=0;mode='image';selectedId=null;renderUI();setStatus('Image ready. Add text or run OCR.')};img.src=url}
async function loadPdf(file){const buf=await file.arrayBuffer();const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.worker.min.mjs';const doc=await pdfjs.getDocument({data:buf}).promise;pages=[];for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),v=p.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;pages.push({dataUrl:c.toDataURL('image/jpeg',.94),width:c.width,height:c.height,items:[]})}mode='pdf';pageIndex=0;selectedId=null;renderUI();setStatus(`${doc.numPages} page${doc.numPages===1?'':'s'} loaded. Add or replace text with overlays.`)}
function renderUI(){ $('fileName').textContent=fileName||'Nothing uploaded';$('fileMeta').textContent=mode==='pdf'?`${pages.length} page${pages.length===1?'':'s'}`:'Image';$('fileIcon').textContent=mode==='pdf'?'PDF':'IMG';$('imageTab').classList.toggle('active',mode==='image');$('pdfTab').classList.toggle('active',mode==='pdf');$('pagesSection').classList.toggle('hidden',mode!=='pdf'||!pages.length);$('exportBtn').textContent=mode==='image'?'Export PNG':'Export PDF';$('exportBtn').disabled=!pages.length;renderPages();renderStage();renderProperties()}
function renderPages(){const g=$('pageGrid');g.innerHTML='';pages.forEach((p,i)=>{const b=document.createElement('button');b.className='pageThumb '+(i===pageIndex?'active':'');b.innerHTML=`<img src="${p.dataUrl}"><span>${i+1}</span>`;b.onclick=()=>{pageIndex=i;selectedId=null;renderUI()};g.appendChild(b)})}
function renderStage(){const stage=$('stage');stage.innerHTML='';if(!pages.length){const e=emptyTemplate.cloneNode(true);e.querySelector('#chooseBtn')?.addEventListener('click',openFile);stage.appendChild(e);return}const p=mode==='image'?pages[0]:pages[pageIndex];const img=new Image();img.className='baseImage';img.src=p.dataUrl;stage.style.aspectRatio=`${p.width}/${p.height}`;stage.appendChild(img);for(const t of p.items){const el=document.createElement('div');el.className='textOverlay '+(selectedId===t.id?'selected':'');el.textContent=t.text;const left=t.x/p.width*100,top=t.y/p.height*100,scale=Math.min(1,850/p.width);el.style.left=left+'%';el.style.top=top+'%';el.style.fontSize=t.fontSize*scale+'px';el.style.color=t.color;el.style.fontWeight=t.bold?'700':'400';el.onpointerdown=e=>dragStart(e,t);stage.appendChild(el)}$('emptyState')?.remove()}
function renderProperties(){const t=state.items.find(x=>x.id===selectedId);$('noSelection').classList.toggle('hidden',!!t);$('properties').classList.toggle('hidden',!t);if(!t)return;$('textInput').value=t.text;$('sizeInput').value=t.fontSize;$('colorInput').value=t.color;$('colorHex').textContent=t.color;$('boldBtn').classList.toggle('active',t.bold)}
function update(id,patch){const i=mode==='image'?0:pageIndex;pages[i].items=pages[i].items.map(t=>t.id===id?{...t,...patch}:t);renderStage();renderProperties()}
$('addTextBtn').onclick=()=>{if(!pages.length)return;const i=mode==='image'?0:pageIndex,t={id:uid(),text:'Edit this text',x:70,y:70,fontSize:34,color:'#111827',bold:false};pages[i].items.push(t);selectedId=t.id;renderUI();setStatus('Text added. Drag it and edit it from the right panel.')}
$('textInput').oninput=e=>selectedId&&update(selectedId,{text:e.target.value});$('sizeInput').oninput=e=>selectedId&&update(selectedId,{fontSize:Number(e.target.value)||34});$('colorInput').oninput=e=>selectedId&&update(selectedId,{color:e.target.value});$('boldBtn').onclick=()=>{const t=state.items.find(x=>x.id===selectedId);if(t)update(selectedId,{bold:!t.bold})};$('deleteBtn').onclick=()=>{if(!selectedId)return;const i=mode==='image'?0:pageIndex;pages[i].items=pages[i].items.filter(t=>t.id!==selectedId);selectedId=null;renderUI()};
function dragStart(e,t){e.stopPropagation();selectedId=t.id;renderProperties();const p=mode==='image'?pages[0]:pages[pageIndex],scale=Math.min(1,850/p.width),sx=e.clientX,sy=e.clientY,ox=t.x,oy=t.y;const mm=ev=>{t.x=Math.max(0,ox+(ev.clientX-sx)/scale);t.y=Math.max(0,oy+(ev.clientY-sy)/scale);renderStage();};const up=()=>{window.removeEventListener('pointermove',mm);window.removeEventListener('pointerup',up);renderProperties()};window.addEventListener('pointermove',mm);window.addEventListener('pointerup',up)}
$('stage').onpointerdown=()=>{selectedId=null;renderStage();renderProperties()};
$('ocrBtn').onclick=async()=>{if(!pages.length||busy)return;busy=true;setStatus('OCR is reading the document…',true);try{const src=mode==='image'?pages[0].dataUrl:pages[pageIndex].dataUrl;const worker=await Tesseract.createWorker('eng');const r=await worker.recognize(src,{}, {blocks:true});await worker.terminate();const p=mode==='image'?pages[0]:pages[pageIndex];const blocks=Array.isArray(r.data?.blocks)?r.data.blocks:[];const lines=blocks.flatMap(b=>(b.paragraphs||[]).flatMap(par=>(par.lines||[]))).filter(l=>l?.text?.trim()&&l?.bbox);for(const l of lines)p.items.push({id:uid(),text:l.text.trim(),x:l.bbox.x0,y:l.bbox.y0,fontSize:Math.max(16,l.bbox.y1-l.bbox.y0),color:'#111827',bold:false});renderUI();setStatus(`OCR found ${lines.length} text line${lines.length===1?'':'s'}. Review before exporting.`)}catch(err){setStatus(err.message||'OCR failed.')}finally{busy=false}};
async function exportImage(){const p=pages[0],c=document.createElement('canvas');c.width=p.width;c.height=p.height;const ctx=c.getContext('2d'),img=new Image();img.src=p.dataUrl;await img.decode();ctx.drawImage(img,0,0);p.items.forEach(t=>{ctx.font=`${t.bold?'700':'400'} ${t.fontSize}px Arial`;ctx.fillStyle=t.color;ctx.fillText(t.text,t.x,t.y+t.fontSize)});download(c.toDataURL('image/png'),`${baseName()}-edited.png`);setStatus('Edited image exported.')}
async function exportPdf(){busy=true;setStatus('Creating edited PDF…',true);try{const {PDFDocument,StandardFonts,rgb}=PDFLib;const out=await PDFDocument.create(),font=await out.embedFont(StandardFonts.Helvetica);for(const p of pages){const jpg=await out.embedJpg(p.dataUrl);const page=out.addPage([p.width,p.height]);page.drawImage(jpg,{x:0,y:0,width:p.width,height:p.height});for(const t of p.items){const hex=t.color.slice(1),r=parseInt(hex.slice(0,2),16)/255,g=parseInt(hex.slice(2,4),16)/255,b=parseInt(hex.slice(4,6),16)/255;const w=Math.max(50,t.text.length*t.fontSize*.58);page.drawRectangle({x:t.x,y:p.height-t.y-t.fontSize*1.2,width:w+8,height:t.fontSize*1.4,color:rgb(1,1,1),opacity:.94});page.drawText(t.text,{x:t.x+3,y:p.height-t.y-t.fontSize,size:t.fontSize,font,color:rgb(r,g,b)})}}const bytes=await out.save();download(URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),`${baseName()}-edited.pdf`);setStatus('Edited PDF exported.')}catch(err){setStatus(err.message||'PDF export failed.')}finally{busy=false}}
function baseName(){return(fileName||'document').replace(/\.[^.]+$/,'')};function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click()}
$('exportBtn').onclick=()=>mode==='image'?exportImage():exportPdf();$('imageTab').onclick=()=>{if(pages.length){mode='image';renderUI()}};$('pdfTab').onclick=()=>{if(pages.length&&fileName.toLowerCase().endsWith('.pdf')){mode='pdf';renderUI()}};
